name: c_builder
version: 1.0.0
description: An API for generating C code in Dart. Especially helpful for compiler development. Supports generating every possible unit of C code.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/c_builder.git
environment:
    sdk: ">=1.8.0 <2.0.0"
dependencies:
  code_buffer: ^1.0.0
  meta: ^1.0.0
dev_dependencies:
  test: ^0.12.0